import "server-only";

import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";

import { env } from "@/env";
import { db } from "@/server/db";
import * as authSchema from "@/server/db/schema/auth";

/**
 * Better Auth owns the `user`, `session`, `account` and `verification` tables.
 * They live in `src/server/db/schema/auth.ts`, generated by:
 *
 *     pnpm auth:generate
 *
 * Re-run that after changing this config (adding a provider or plugin can add
 * columns), then `pnpm db:generate` to produce the SQL migration.
 */
export const auth = betterAuth({
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.NEXT_PUBLIC_APP_URL,
  database: drizzleAdapter(db, { provider: "pg", schema: authSchema }),
  emailAndPassword: {
    enabled: true,
    /**
     * No mail transport is wired up yet, so requiring verification would lock
     * every new account out. Turn this on when email sending exists.
     */
    requireEmailVerification: false,
  },
  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // refresh the expiry at most once a day
  },
  /** Lets Better Auth set cookies from server actions and route handlers. */
  plugins: [nextCookies()],
});

export type Session = typeof auth.$Infer.Session;
