import { z } from "zod";

import { isIsoDate } from "@/lib/dates";
import { CURRENCIES, parseAmount } from "@/lib/money";

/**
 * Input pieces shared by more than one router, so that a date or an amount
 * means the same thing wherever it is accepted.
 */

export const currencyInput = z.enum(CURRENCIES);

export const nameInput = z.string().trim().min(1, "Name is required").max(120);

/** A calendar day as `YYYY-MM-DD`, which is what `<input type="date">` submits. */
export const isoDateInput = z.string().refine(isIsoDate, "Enter a date as YYYY-MM-DD");

/**
 * Money arrives as the text the user typed and leaves as integer minor units.
 * Parsing on the server rather than in the form means the paste importer and
 * every form agree about what `1.234,56` means, and no amount is ever carried
 * across the wire as a float.
 */
export const amountInput = z
  .string()
  .trim()
  .refine((value) => parseAmount(value) !== null, "Enter an amount, such as 1234.56")
  .transform((value) => parseAmount(value) ?? 0);

/** Ids are generated by us, so shape is all there is to check. */
export const idInput = z.string().min(1).max(64);
